/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'assignment_flutter_mostafizur';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String DOKAN_LOGO_COLOR = 'assets/images/Dokan-Logo-color.png';
  static const String FB_ICON = 'assets/images/fb_icon.svg';
  static const String G_LOGO = 'assets/images/g_logo.png';
  static const String GMAIL = 'assets/images/gmail.svg';
  static const String GOOGLE_ICON = 'assets/images/google_icon.svg';
  static const String PASSWORD = 'assets/images/password.svg';
  static const String PASSWORD_VISIBILE = 'assets/images/password_visibile.svg';
  static const String USER_ICON = 'assets/images/user_icon.svg';
}
