/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'assignment_flutter_mostafizur';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String PRODUCT2 = 'assets/images/product2.png';
  static const String RESPONSE = 'assets/json/response.json';
}
